= 4. Coordinate Dataflow

////
Copyright 2020 Jonas Bonér & Reactive Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

include::ROOT:partial$include.adoc[]

_Orchestrate a continuous steady flow of information_


Reactive shines in the creation of data-driven applications through the composition of components in workflows. Thinking in terms of dataflow, how the data flows through the system, what behavior it is triggering and where, and how components are https://en.wikipedia.org/wiki/Causality[causally related] https://en.wikipedia.org/wiki/Causality[{tab}, window="new tab"] allows focusing on the _behavior_ instead of the only on the _structure_. Orchestrate workflow and integration by letting components (or subsystems) subscribe to each other’s _event streams_, consuming on-demand the asynchronously published facts.

Consumers should control the rate of consumption — which may well be decoupled from the rate of production, depending on the use-case. It is impossible to overwhelm a consumer that controls its own rate of consumption. This is one of the reasons some architectures employ message queues: they absorb the extra load and allow consumers to drain the work at their leisure. Some architectures design “poison-pill” messages as a way to altogether cancel the production of messages. This combination—a consumer that controls its rate of consumption and an out-of-band mechanism to halt the rate of production—supports flow control. Flow control is an obvious win at the systems architecture level, but all too easy to ignore at lower levels. 

Flow control needs to be managed end-to-end with all its participants playing ball lest overburdened consumers fail or consume resources without bound. Libraries that support it natively and compose using standardized protocols can help immensely—such as the https://www.reactive-streams.org/[Reactive Streams protocol] https://www.reactive-streams.org/[{tab}, window="new tab"] with its wide range of implementations (e.g. https://projectreactor.io/[Reactor], https://projectreactor.io/[{tab}, window="new tab"] https://github.com/ReactiveX/RxJava[RxJava], https://github.com/ReactiveX/RxJava[{tab}, window="new tab"] https://vertx.io/[Vert.x], https://vertx.io/[{tab}, window="new tab"] https://doc.akka.io/docs/akka/current/stream/index.html[Akka Streams], https://doc.akka.io/docs/akka/current/stream/index.html[{tab}, window="new tab"] https://smallrye.io/smallrye-mutiny/[Mutiny], https://smallrye.io/smallrye-mutiny/[{tab}, window="new tab"] and http://rsocket.io/[RSocket] http://rsocket.io/[{tab}, window="new tab"]). 

Reactive Streams employ a scheme called https://www.reactivemanifesto.org/glossary#Back-Pressure[back-pressure] https://www.reactivemanifesto.org/glossary#Back-Pressure[{tab}, window="new tab"] in which the producer is forced to slow down when the consumer cannot keep up. Another scheme is to place a message queue between producer and consumer and react to the utilization of this queue, for example by giving the consumer more resources or by slowing down or degrading the functionality of the producer.

Particular care for the dataflows needs to be taken at the xref:edge-native:index.adoc[edges], where components compose and interact—with each other or with third-party systems. Establishing protocols for _graceful degradation_ and flow control means decreasing the likelihood of failure, and when it strikes—which it inevitably will—it is beneficial to have a control mechanism in place to manage it. 