= The Reactive Patterns

////
Copyright 2020 Jonas Bonér & Reactive Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

include::ROOT:partial$include.adoc[]


The following patterns can help us codify and apply the xref:principles:index.adoc[Reactive Principles] in our applications and systems. Not all of these patterns apply to all problems, use-cases, and contexts, but should be seen as tools in your toolbox to be used and applied selectively when needed. 

It is not meant to be fixed set of patterns but a starting point for a growing and living patterns catalog that are maintained by the community. If you have ideas for new patterns or want to help out improving the existing ones (elaborate on the pattern discussion, add examples, or even sample code) then please read xref:ROOT:contributing.adoc[How to Contribute to this Document]. We need your help.
 

* xref:partition-state.adoc[Partition State]
* xref:communicate-facts.adoc[Communicate Facts]
* xref:isolate-mutations.adoc[Isolate Mutations]
* xref:coordinate-dataflow.adoc[Coordinate Dataflow]
* xref:localize-state.adoc[Localize State]
* xref:observe-communications.adoc[Observe Communications]
