= 3. Isolate Mutations

include::ROOT:partial$include.adoc[]

_Contain and isolate mutable state using bulkheads_


When you have to use mutable state, don’t share it. Instead contain it together with the associated behavior, using isolated and partitioned compartments, separated by https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead[“bulkheads”] https://docs.microsoft.com/en-us/azure/architecture/patterns/bulkhead[{tab}, window="new tab"] and thus adopting a https://en.wikipedia.org/wiki/Shared-nothing_architecture[shared-nothing architecture]. https://en.wikipedia.org/wiki/Shared-nothing_architecture[{tab}, window="new tab"] This contains failure, prevents it from propagating outside the failed component, limits its scope, and localizes it to make it easier to pinpoint and manage. It also avoids minor issues leading to “cascading failures” and taking down an entire system. For example, recall that validation errors are not failures but are part of the normal interaction protocol of your stateful component.

Bulkheads are most easily installed by having the compartments communicate using https://www.reactivemanifesto.org/glossary#Message-Driven[asynchronous messaging], https://www.reactivemanifesto.org/glossary#Message-Driven[{tab}, window="new tab"] which introduces a protocol boundary between the components, isolating them in both xref:principles:decouple-time.adoc[_time_] and xref:principles:decouple-space.adoc[_space_].  Asynchronous messaging also enables observing the fluctuating demands, avoiding flooding a bulkhead, and providing a unit of replication if needed. 

Only use mutable state for local computations, within the _consistency boundary_ of the bulkheaded component—a _unit of consistency_ that provides a safe haven for mutations, completely unobservable by the rest of the world. When the component is done with the local processing and ready to tell the world about its results, then it creates an immutable value representing the result—a _fact_— and publishes it to the world. 

The bulkheaded components should ideally use single-threaded execution to simplify the programming model and avoid concurrency-related problems such as deadlocks, race conditions, and corrupt data. For example, https://nodejs.org/[Node.js], https://nodejs.org/[{tab}, window="new tab"] https://akka.io/[Akka], https://akka.io/[{tab}, window="new tab"] https://lmax-exchange.github.io/disruptor/[Disruptor], https://lmax-exchange.github.io/disruptor/[{tab}, window="new tab"] or implementation of the https://en.wikipedia.org/wiki/Reactor_pattern[Reactor] https://en.wikipedia.org/wiki/Reactor_pattern[{tab}, window="new tab"] Pattern and its variants offer this functionality.

In this model, others can rely on stable and immutable values for their reasoning, whereas each component can internally still safely benefit from the advantages of mutability (like the simplicity of coding and algorithmic efficiency), strong consistency (providing https://en.wikipedia.org/wiki/ACID[ACID] https://en.wikipedia.org/wiki/ACID[{tab}, window="new tab"] semantics), and reduced coordination and contention (through the https://mechanical-sympathy.blogspot.com/2011/09/single-writer-principle.html[Single Writer Principle] https://mechanical-sympathy.blogspot.com/2011/09/single-writer-principle.html[{tab}, window="new tab"]).