= 5. Localize State

////
Copyright 2020 Jonas Bonér & Reactive Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

include::ROOT:partial$include.adoc[]

_Take ownership of data by co-locating state and processing_


In data-intensive applications and use-cases, it is often beneficial to co-locate state and processing, maintaining great https://en.wikipedia.org/wiki/Locality_of_reference[locality of reference] https://en.wikipedia.org/wiki/Locality_of_reference[{tab}, window="new tab"] while providing a https://en.wikipedia.org/wiki/Single_source_of_truth[single source of truth]. https://en.wikipedia.org/wiki/Single_source_of_truth[{tab}, window="new tab"] Co-location allows for low-latency and high-throughput data processing, and more evenly distributed workloads.

One way of achieving co-location is to _move the processing to the state_. This can be effectively achieved by using https://doc.akka.io/docs/akka/snapshot/typed/cluster-sharding.html[cluster sharding] https://doc.akka.io/docs/akka/snapshot/typed/cluster-sharding.html[{tab}, window="new tab"] (e.g. sharding on entity key) of in-memory data where the business logic is executed in-process on each shard, avoiding read and write contention. Ideally, the in-memory data should represent the single source of truth by mapping to the underlying storage in a _strongly consistent_ fashion (e.g. using patterns like https://martinfowler.com/eaaDev/EventSourcing.html[Event Sourcing] https://martinfowler.com/eaaDev/EventSourcing.html[{tab}, window="new tab"] and https://martinfowler.com/bliki/MemoryImage.html[Memory Image]). https://martinfowler.com/bliki/MemoryImage.html[{tab}, window="new tab"] 

Co-location is different from, and complementary to, https://en.wikipedia.org/wiki/Cache_(computing)[caching], https://en.wikipedia.org/wiki/Cache_(computing)[{tab}, window="new tab"] where you maintain read-only copies of the most frequently used data close to its processing context. Caching is extremely useful in some situations (in particular when the use-case is read-heavy). But it adds complexity around staying in sync with its master data, which makes it hard to maintain the desired level of consistency, and therefore cached data cannot be used as the single source of truth.

Another way to get co-location is to _move the state to the processing_. This can be achieved by https://en.wikipedia.org/wiki/Replication_(computing)[replicating the data] https://en.wikipedia.org/wiki/Replication_(computing)[{tab}, window="new tab"] to all nodes where the business logic might run while leveraging techniques that ensure _eventually consistent_ _convergence_ of the data (e.g. using https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type[CRDTs] https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type[{tab}, window="new tab"] with https://en.wikipedia.org/wiki/Gossip_protocol[gossip protocols] https://en.wikipedia.org/wiki/Gossip_protocol[{tab}, window="new tab"]). These techniques have the additional advantage of ensuring high degrees of availability without the need for additional storage infrastructure and can be used to maintain data consistency across all levels of the stack; across components, nodes, data-centers, and clients where strong consistency is not required.