= README


The source files for this guide use asciidoc syntax and the project is configured to build with Antora. To review and suggest changes, we recommend building the HTML files locally. 


== Building the guide locally

To build this guide locally, follow these steps:

. Follow the steps to install Antora that are described here: https://docs.antora.org/antora/2.0/install/install-antora/.
. Run `npm install -g asciidoc-link-check`
. Clone https://github.com/lightbend/lightbend-platform-docs locally

You can then use `make` to build the docs, or if you want to view TODO and REVIEWER notes in the output, use author mode. The `Makefile` runs Antora and optionally checks for broken links and leftover TODO and REVIEWER comments. Author mode runs Antora using the `author-mode-site.yml` configuration, which defines the `todo` and `reviewer` attributes so those comments display in the output. Either way, Antora should generate the HTML files in a `build/site` directory. You can view the guide by opening `build/site/introduction/index.html`.

TODO: add info about installing the antora-lunr integration

The command for building with search enabled:

````
DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr NODE_PATH="$(npm -g root)" antora --generator antora-site-generator-lunr playbook.yml
````

TODO: The following will need to be updated

=== To use `make`

In a command prompt:

. Change into the branch's top directory.
. Run the following command for the complete build:
+
[source,bash]
----
make
----
+
or to quickly regenerate the site without running all of the checks:
+
[source,bash]
----
make html
----



== For reference

Antora is built on top of Asciidoctor. One of the main differences between Asciidoctor and Antora is that Antora requires a specfic directory structure. If you are new to Antora and asciidoc, the following references might be helpful:

* https://docs.antora.org/antora/2.0/
* https://asciidoctor.org/docs/
* http://asciidoc.org/
