= II. Accept Uncertainty

////
Copyright 2020 Jonas Bonér & Reactive Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

include::ROOT:partial$include.adoc[]

_Build reliability despite unreliable foundations_


As soon as we cross the boundary of the local machine, or of the container, we enter a vast and endless ocean of nondeterminism: the world of distributed systems. It is a scary world in which systems can fail in the most spectacular and intricate ways, where information becomes lost, reordered, and corrupted, and where failure detection is a guessing game. It’s a world of uncertainty. 

Most importantly, there is no “now”. The present is relative and subjective, framed by the viewpoint of the observer. The fundamental problem of this world, due to the lack of consistent and reliable shared memory, is the inability to know what is happening on another node _now_. We must acknowledge that we cannot wait indefinitely for the information we need for a decision. As a consequence, our algorithms will lack information due to faulty hardware, unreliable networks, or the plain physical problem of communication latency. Data is out of date by the time it’s acknowledged and we are forced to deal with a fragmented and unevenly outdated state of things.

Even though there are well established distributed algorithms to tame this uncertainty and produce a strongly consistent view of the world, those algorithms tend to exhibit poor performance and scalability characteristics and imply unavailability during network partitions. As a result, for distributed systems, we have had to give up most of them as a necessary tradeoff to achieve responsiveness, moving us to agree to a significantly lesser degree of consistency, such as causal, eventual, and others, and accept the higher level of uncertainty that comes with them.

This has a lot of implications: we can’t always trust _time_ as measured by clocks and timestamps, or _order_ (https://en.wikipedia.org/wiki/Causality[causality] https://en.wikipedia.org/wiki/Causality[{tab}, window="new tab"] might not even exist).  Accepting this uncertainty, we have to use strategies to cope with it. For example: rely on https://en.wikipedia.org/wiki/Logical_clock[logical clocks] https://en.wikipedia.org/wiki/Logical_clock[{tab}, window="new tab"] (such as https://en.wikipedia.org/wiki/Vector_clock[vector clocks] https://en.wikipedia.org/wiki/Vector_clock[{tab}, window="new tab"]); when appropriate use https://en.wikipedia.org/wiki/Eventual_consistency[eventual consistency] https://en.wikipedia.org/wiki/Eventual_consistency[{tab}, window="new tab"] (e.g. certain https://en.wikipedia.org/wiki/NoSQL[NoSQL] https://en.wikipedia.org/wiki/NoSQL[{tab}, window="new tab"] databases and https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type[CRDTs] https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type[{tab}, window="new tab"]); and make sure our communication protocols are https://en.wikipedia.org/wiki/Associative_property[associative] https://en.wikipedia.org/wiki/Associative_property[{tab}, window="new tab"] (batch-insensitive), https://en.wikipedia.org/wiki/Commutative_property[commutative] https://en.wikipedia.org/wiki/Commutative_property[{tab}, window="new tab"] (order-insensitive), and http://bit.ly/2veea5I[idempotent] http://bit.ly/2veea5I[{tab}, window="new tab"] (duplication-insensitive).

The key is to manage uncertainty directly in the application architecture. To design resilient autonomous components that publish their protocols to the world—protocols that clearly define what they can promise, what commands and events will be accepted, and, as a result of that, what behavior will trigger and how the data model should be used. The timeliness and assessed accuracy of underlying information should be visible to other components where appropriate so that they — or the end-user — can judge the reliability of the current system state.
