= IV. Assert Autonomy
include::ROOT:partial$include.adoc[]

_Design components that act independently and interact collaboratively_

The components of a larger system can only stay responsive to the degree of autonomy they have from the rest of the system. In Reactive applications, autonomy is achieved by clearly defining the component boundaries, who owns what data and how the owners make it available, and by designing them such that each party is afforded the necessary degree of freedom to make its own decisions. +
When a service calls  upon another component, that component must have the ability to communicate back momentary degradations, for example, caused by overload or faulty dependencies. And it must have the freedom to not respond when that is appropriate, most notably when shedding heavy load. This requires the protocol between these components to be asynchronous and event-based, even when the used API looks synchronous — after all, we can only contain component-level failure when the protocol foresees the possibility of unsuccessful or late responses. 

Another aspect of autonomy is that the boundary between the two components is crossed only via the documented protocols; there cannot be other side-channels. Only with this discipline is it possible to reason about the collaboration and potentially verify it formally (for example using https://groups.inf.ed.ac.uk/abcd/[Session Types] https://groups.inf.ed.ac.uk/abcd/[{tab}, window="new tab"]). Many times the protocol will be trivial, like the https://en.wikipedia.org/wiki/Request%E2%80%93response[request-response] https://en.wikipedia.org/wiki/Request%E2%80%93response[{tab}, window="new tab"] message pairs, but in other cases, it may involve back-pressure (as in https://www.reactive-streams.org/[Reactive Streams] https://www.reactive-streams.org/[{tab}, window="new tab"]) or even complex consensus protocols between multiple parties. The important part is that the protocol is fully specified, respecting the autonomy of the participants within the communication design. 

Valuable patterns that foster autonomy include: https://martinfowler.com/bliki/DomainDrivenDesign.html[domain-driven design], https://martinfowler.com/bliki/DomainDrivenDesign.html[{tab}, window="new tab"] https://martinfowler.com/eaaDev/EventSourcing.html[event-sourcing], https://martinfowler.com/eaaDev/EventSourcing.html[{tab}, window="new tab"] and https://martinfowler.com/bliki/CQRS.html[CQRS]. https://martinfowler.com/bliki/CQRS.html[{tab}, window="new tab"] Communicating fully self-contained _facts_ — modeled closely after the underlying business domain — gives the recipient the power to make their own decisions without having to ask again for more information. CQRS separates concerns by making decisions about one part of the system in one location (one component), which can then readily be disseminated and acted upon elsewhere—possibly at a much later time.