= VI. Decouple Time

////
Copyright 2020 Jonas Bonér & Reactive Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

include::ROOT:partial$include.adoc[]

_Process asynchronously to avoid coordination and waiting_

It’s been said that “silence is golden”, and it is as true in software systems as in the real world.  https://en.wikipedia.org/wiki/Amdahl%27s_law[Amdahl’s Law] https://en.wikipedia.org/wiki/Amdahl%27s_law[{tab}, window="new tab"] and the http://www.perfdynamics.com/Manifesto/USLscalability.html[Universal Scalability Law] http://www.perfdynamics.com/Manifesto/USLscalability.html[{tab}, window="new tab"] show that the ceiling on scalability can be lifted by avoiding needless communication, coordination, and waiting. 

There are still times when we have to communicate and coordinate our actions. The problem with blocking on resources—for example https://en.wikipedia.org/wiki/Input/output[I/O] https://en.wikipedia.org/wiki/Input/output[{tab}, window="new tab"] but also when calling a different service—is that the caller, including the thread it is executing on, is held hostage waiting for the resource to become available. During this time the calling component (or a part thereof) is unavailable for other requests.

This can be mitigated or avoided by employing _temporal decoupling_. Temporal decoupling helps break the time availability dependency between remote components. When multiple components synchronously exchange messages, it presumes the availability and reachability of all these components for the duration of the exchange. This is a fragile assumption in the context of distributed systems, where we can’t ensure the availability or reachability of all components in a system at all times. By introducing temporal decoupling in our communication protocols, one component does not need to assume and require the availability of the other components. It makes the components more independent and autonomous and, as a consequence, the overall system more reliable. Popular techniques to implement temporal decoupling include durable message queues, append-only journals, and publish-subscribe topics with a retention duration.

With temporal decoupling, we give the caller the option to perform other work, https://www.reactivemanifesto.org/glossary#Asynchronous[asynchronously] https://www.reactivemanifesto.org/glossary#Asynchronous[{tab}, window="new tab"], rather than be blocked waiting on the resource to become available. This can be achieved by allowing the caller to put its request on a queue, register a https://en.wikipedia.org/wiki/Callback_(computer_programming)[callback] https://en.wikipedia.org/wiki/Callback_(computer_programming)[{tab}, window="new tab"] to be notified later, return immediately, and continue execution (e.g., https://www.reactivemanifesto.org/glossary#Non-Blocking[non-blocking I/O] https://www.reactivemanifesto.org/glossary#Non-Blocking[{tab}, window="new tab"]). A great way to orchestrate callbacks is to use a https://en.wikipedia.org/wiki/Finite-state_machine[Finite State Machine] https://en.wikipedia.org/wiki/Finite-state_machine[{tab}, window="new tab"] (FSM), other techniques include https://en.wikipedia.org/wiki/Futures_and_promises[Futures/Promises] https://en.wikipedia.org/wiki/Futures_and_promises[{tab}, window="new tab"], https://en.wikipedia.org/wiki/Dataflow_programming[Dataflow Variables],  https://en.wikipedia.org/wiki/Dataflow_programming[{tab}, window="new tab"] https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await[Async/Await] https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await[{tab}, window="new tab"], https://en.wikipedia.org/wiki/Coroutine[Coroutines] https://en.wikipedia.org/wiki/Coroutine[{tab}, window="new tab"], and composition of https://blog.colinbreck.com/maximizing-throughput-for-akka-streams/[asynchronous functional combinators] https://blog.colinbreck.com/maximizing-throughput-for-akka-streams/[{tab}, window="new tab"] in streaming libraries.

The aforementioned programming techniques serve the higher-level purpose of affording each component in a Reactive application more freedom in choosing to process incoming information in their own time, according to their own prioritization. As such, this decoupling also gives components more autonomy.