= VII. Decouple Space

////
Copyright 2020 Jonas Bonér & Reactive Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

include::ROOT:partial$include.adoc[]

_Create flexibility by embracing the network_


We can only create a resilient system if we allow it to live in multiple locations so that it can function when parts of the underlying hardware malfunction or are inaccessible; in other words, we need to distribute the parts across space. Once distributed, the now _autonomous_ components collaborate, as loosely coupled as is possible for the given use-case, to make maximal use of the newly won independence from one specific location.

This _spatial decoupling_ makes use of network communication to connect the potentially remote pieces again. Since all networks function by passing messages between nodes and since this message-passing takes time, spatial decoupling introduces asynchronous https://reactivemanifesto.org/glossary#Message-Driven[message-passing] https://reactivemanifesto.org/glossary#Message-Driven[{tab}, window="new tab"] on a foundational level. Higher-level representations of this aspect are https://grpc.io/[gRPC], https://grpc.io/[{tab}, window="new tab"] https://nats.io/[NATS.io], https://nats.io/[{tab}, window="new tab"] https://kafka.apache.org/[Apache Kafka], https://kafka.apache.org/[{tab}, window="new tab"] HTTP & REST — the question of whether and how the asynchronous nature of the network is surfaced in the local APIs is up to each component to decide.

A key aspect of asynchronous messaging and/or APIs is that it makes the network, with all its constraints, explicit and first-class in the design. It forces you to _design for failure_ and _uncertainty_ instead of pretending that the network is not there and trying to hide it behind a http://bit.ly/2ve6r7J[leaky local abstraction], http://bit.ly/2ve6r7J[{tab}, window="new tab"] (e.g. network-attached disks), just to see it fall apart in the face of partial failures, message loss, or reordering.

It also allows for https://www.reactivemanifesto.org/glossary#Location-Transparency[location transparency], https://www.reactivemanifesto.org/glossary#Location-Transparency[{tab}, window="new tab"] which gives you one single abstraction for all component interactions, regardless of whether the component is co-located on the same physical machine, in another rack, or even another data center. Asynchronous APIs allow cloud infrastructures such as discovery services and load balancers to route requests to wherever the container or VM is running while embracing the likelihood of ever-changing latency and failure characteristics. This provides one programming model with a single set of semantics regardless of how the system is deployed or what topology it currently has (which can change with its usage).

Spatial decoupling enables replication, which ultimately increases the resilience of the system and availability. By running multiple instances of a component, these instances can share the load. Thanks to location transparency, the rest of the system does not need to know where these instances are located but the capacity of the system can be increased transparently, on-demand. If one instance crashes or is undeployed, the other replicas continue to operate and share the load. This capability to fail-over is essential to avoid service disruption. 
